import 'package:ticket_booking_app/features/home/model/airport_model.dart';
import 'package:ticket_booking_app/features/home/model/ticket_model.dart';
import 'package:ticket_booking_app/features/home/model/user_ticket_model.dart';

List<AirportModel> airports = [
  // 'Chennai',
  // 'Banglore',
  // 'Delhi',
  // 'Mumbai',
  AirportModel(
    cityName: 'Chennai',
    airPortName: 'Chennai International Airport',
    codeName: 'CIA',
  ),
  AirportModel(
    cityName: 'Banglore',
    airPortName: 'Banglore International Airport',
    codeName: 'BIA',
  ),
  AirportModel(
    cityName: 'Mumbai',
    airPortName: 'Mumbai International Airport',
    codeName: 'BIA',
  ),
  AirportModel(
    cityName: 'Delhi',
    airPortName: 'Delhi Central International Airport',
    codeName: 'DCIA',
  ),
];

UserTicketModel userTicketModel = UserTicketModel(
  departForm: airports[1].cityName,
  departTo: airports[2].cityName,
  departDate: DateTime.now(),
  passengersCount: 1,
  adultCount: 1,
  infantCount: 0,
  childrenCount: 0,
);

List<TicketModel> flightList = [
  TicketModel(
    from: airports[0].cityName,
    onTo: airports[1].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'abc',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[0].cityName,
    onTo: airports[1].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'bckd',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[0].cityName,
    onTo: airports[1].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'dleos',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[1].cityName,
    onTo: airports[2].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'air',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[1].cityName,
    onTo: airports[2].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'ind',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[1].cityName,
    onTo: airports[2].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'latest',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[2].cityName,
    onTo: airports[3].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'var',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[2].cityName,
    onTo: airports[3].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'local',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[2].cityName,
    onTo: airports[3].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'scal',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[3].cityName,
    onTo: airports[0].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'p90',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[3].cityName,
    onTo: airports[1].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'groza',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
  TicketModel(
    from: airports[3].cityName,
    onTo: airports[2].cityName,
    flightName: 'Air India',
    availability: [0, 1, 2, 3, 4, 5, 6],
    seaterlId: 'mp5',
    departureTime: '10:00',
    arraivalTime: '14:00',
    travelTime: '50 mins',
    ecoTicketPrice: 2000,
    bnsTicketPrice: 3600,
  ),
];
