import 'package:ticket_booking_app/core/models/seat_model.dart';

List<SeatModel> seatList() {
  return [
    SeatModel(
      id: 0,
      seatName: 'A1',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 1,
      seatName: 'A2',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 2,
      seatName: 'A3',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 3,
      seatName: 'A4',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 4,
      seatName: 'A5',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 5,
      seatName: 'A6',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 6,
      seatName: 'A7',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 7,
      seatName: 'A8',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 8,
      seatName: 'B1',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 9,
      seatName: 'B2',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 10,
      seatName: 'B3',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 11,
      seatName: 'B4',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 12,
      seatName: 'B5',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 13,
      seatName: 'B6',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 14,
      seatName: 'B7',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 15,
      seatName: 'B8',
      isOccupied: false,
      isSelected: false,
      side: 'L',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 16,
      seatName: 'C1',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 17,
      seatName: 'C2',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 18,
      seatName: 'C3',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 19,
      seatName: 'C4',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 20,
      seatName: 'C5',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 21,
      seatName: 'C6',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 22,
      seatName: 'C7',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 23,
      seatName: 'C8',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 24,
      seatName: 'D1',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 25,
      seatName: 'D2',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 26,
      seatName: 'D3',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 27,
      seatName: 'D4',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'business',
      price: 2000,
    ),
    SeatModel(
      id: 28,
      seatName: 'D5',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 29,
      seatName: 'D6',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 30,
      seatName: 'D7',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
    SeatModel(
      id: 31,
      seatName: 'D8',
      isOccupied: false,
      isSelected: false,
      side: 'R',
      classCategory: 'economy',
      price: 2000,
    ),
  ];
}
